frontend/app.py
from flask import Blueprint, render_template
from jinja2 import Environment, PackageLoader
from frontend.clients.user_client import UserClient
from frontend.config import ENDPOINT


env = Environment(loader=PackageLoader('frontend', 'templates'))

uapp = Blueprint('user', __name__)


@uapp.route('/')
def index():
    return render_template('index.html')


@uapp.route('/users')
def user_registration():
    users_client = UserClient(ENDPOINT)
    all_users = users_client.get_all()
    template = env.get_template('name.html')
    return template.render(users=all_users)

frontend/views/app.py
import logging
from flask import Blueprint, redirect, url_for
from frontend.clients.plan_client import PlanningClient

from datetime import datetime
from frontend.clients.user_client import UserClient
from frontend.config import ENDPOINT

view = Blueprint('app', __name__)

logger = logging.getLogger(__name__)

users_client = UserClient(ENDPOINT)
plan_client = PlanningClient(ENDPOINT)


@view.route('/')
def index():
    plan = plan_client.add(name='', date=datetime.now())
    logger.info(plan)
    return redirect(url_for('plannings.plan', planning_id=plan.uid))

frontend/views/plannings.py
import logging

from flask import (Blueprint, abort, redirect, render_template, request,
                   session, url_for)

from frontend.clients.plan_client import PlanningClient
from frontend.clients.task_client import TaskClient
from frontend.clients.user_client import UserClient
from frontend.config import ENDPOINT
from frontend.views.tasks import task_view

view = Blueprint('plannings', __name__)
view.register_blueprint(task_view, url_prefix='/<int:planning_id>/tasks')

logger = logging.getLogger(__name__)

plan_client = PlanningClient(ENDPOINT)
user_client = UserClient(ENDPOINT)
task_client = TaskClient(ENDPOINT)


@view.route('/<int:planning_id>')
def plan(planning_id: int):
    username, userid = session.get('username'), session.get('userid')
    planning = plan_client.get_by_id(planning_id)
    if not planning:
        abort(404, "Planning not found")

    tasks = task_client.get_all_tasks(planning_id)
    users = user_client.get_all_users(planning_id)
    users_set = {user.uid for user in users}

    if userid and username and userid not in users_set:
        username, userid = None, None

    return render_template(
        'plannings.html',
        username=username,
        userid=userid,
        users=users,
        tasks=tasks,
        planning_id=planning_id
    )


@view.post('/<planning_id>/tasks/')
def create_task(planning_id):
    logger.info('task created %s %s', planning_id, request.form['task'])
    task_client.add_task(name=request.form['task'], planning_id=planning_id)
    return redirect(url_for('plannings.plan', planning_id=planning_id))


@view.post('/<planning_id>/users/')
def create_user(planning_id):
    logger.info('user created %s', planning_id)

    user = user_client.add_user(name=request.form['user'], planning_id=planning_id)

    session['userid'] = user.uid
    session['username'] = user.name

    return redirect(url_for('plannings.plan', planning_id=planning_id))

frontend/views/tasks.py
import logging
from typing import Optional

from flask import Blueprint, redirect, render_template, request, session, url_for

from frontend.clients.estimate_client import EstimateClient
from frontend.clients.plan_client import PlanningClient
from frontend.clients.task_client import TaskClient
from frontend.clients.user_client import UserClient
from frontend.config import ENDPOINT
from frontend import schemas

task_view = Blueprint('tasks', __name__)

logger = logging.getLogger(__name__)

plan_client = PlanningClient(ENDPOINT)
user_client = UserClient(ENDPOINT)
task_client = TaskClient(ENDPOINT)
estimate_client = EstimateClient(ENDPOINT)


ESTIMATES = ['1', '2', '3', '5', '8', '13', '21', '?']


@task_view.get('/<int:task_id>')
def get_task_by_id(planning_id: int, task_id: int):
    task = task_client.get_by_id(task_id, planning_id)
    estimates = get_estimates(planning_id=planning_id, task_id=task_id)

    if get_user_estimate(estimates):
        return final_score(
            planning_id=planning_id,
            task=task,
            estimates=estimates,
        )

    logger.info(task)
    return render_template(
        'estimates.html',
        task_id=task.uid,
        planning_id=planning_id,
        estimates=ESTIMATES,
        username=session['username'],
    )


@task_view.get('/<int:task_id>/<estimate>')
def set_estimate(planning_id: int, task_id: int, estimate: str):
    task_client.set_estimates(
        planning_id=planning_id,
        task_id=task_id,
        user_id=session['userid'],
        storypoint=int(estimate) if estimate != '?' else None,
    )

    return redirect(url_for(
        'plannings.tasks.get_task_by_id',
        planning_id=planning_id,
        task_id=task_id,
    ))


def get_estimates(planning_id: int, task_id: int) -> dict[int, schemas.Estimate]:
    estimates = estimate_client.get_estimates(planning_id=planning_id, task_id=task_id)
    return {estimate.user_id: estimate for estimate in estimates}


def get_user_estimate(estimates: dict[int, schemas.Estimate]) -> Optional[int]:
    userid = session['userid']
    estimate = estimates.get(userid)
    return estimate.storypoint if estimate else None


def final_score(planning_id: int, task: schemas.Task, estimates: dict[int, schemas.Estimate]):
    users = user_client.get_all_users(planning_id)
    users_map = {user.uid: user for user in users}

    user_estimates = [
        (users_map[estimate.user_id].name, estimate.storypoint or '?')
        for _, estimate in estimates.items()
    ]

    return render_template(
        'final_score.html',
        planning_id=planning_id,
        task=task,
        user_estimates=user_estimates,
        user_estimate=get_user_estimate(estimates) or '?',
        username=session['username'],
    )


@task_view.post('/<int:task_id>/new-score')
def set_score(planning_id: int, task_id: int):
    task_client.set_score(
        planning_id=planning_id,
        task_id=task_id,
        storypoint=int(request.form['score']),
    )
    return redirect(url_for('plannings.plan', planning_id=planning_id))

frontend/templates/estimates.html
</html>
<!DOCTYPE html>
<html lang="en">
<head>
  <title> Oценка задачи</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=2">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
   <!-- <style>
        div {
            width: 27%; /* Ширина */
            float: left; /* Выстраиваем элементы по горизонтали */
            margin: 0 0 0 3.0%; /* Отступ слева */
            background: #d1c9c9; /* Цвет фона */
            border-radius: 50px; /* Радиус скругления */
            padding: 3%; /* Поля */
        }
	</style> -->
</head>
<body>
    <div class="jumbotron" style="text-indent: 15px;">
        <h1>Оценка задачи</h1>
    </div>
    <div class="col-sm-offset-2 col-sm-10" style="position: relative; left: 1%;">
        <button type="button" class="btn btn-outline-dark"> {{ username }} </button>
    </div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-4 justify-content-md-center">
        {% for estimate in estimates %}
            <a href="{{ url_for('plannings.tasks.set_estimate', planning_id=planning_id, task_id=task_id, estimate=estimate) }}">
                <div class="container-fluid" style="margin-bottom: 16px; margin-top: 25px;">
                    <div class="card"
                        style="
                        height: 200;
                        width: 200;
                        background: gray;
                        box-shadow: 0 14px 28px rgba(0,0,0,0.25),
                        0 10px 10px rgba(0,0,0,0.22) "  >
                        <div class="card-img-overlay d-flex align-items-center justify-content-center"
                    >
                            <h2 class="card-text text-white" > {{ estimate }} </h2>
                        </div>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>

</body>
</html>

frontend/templates/final_score.html
</html>
<!DOCTYPE html>
<html lang="en">
<head>
  <title> Final Score </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
      >
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
   <style>
        div {
            width: 33%; /* Ширина */
            float: left; /* Выстраиваем элементы по горизонтали */
            margin: 0 0 0 3.0%; /* Отступ слева */
            background: #d1c9c9; /* Цвет фона */
            border-radius: 5px; /* Радиус скругления */
            padding: 3%; /* Поля */
            height:120px;
            line-height:100px;
            padding: 1rem;
            margin-bottom: 2rem;
            box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
        }
	</style>
</head>
    <body>
        <div1 class="conteiner">

        <div1 class="jumbotron" style="text-indent: 15px;">
            <h2>Final score</h2>
            <div1 class="button" style="position: relative; left: 1%;">
            <button type="card" class="btn btn-outline-dark" >{{ username }}</button>
            <div1>
        </div1>
        </div1>
        <div class="container mt-3" style= "height:1px; width: 4000px;">
        </div>
                <div1 class="conteiner">
                    <div1 class=" card" style="background: white;" >
                        <div1 class="card" style="font-size: 13pt;">
                            <div class="card text-center ">
                            {{ task.name }}
                            </div>
                        </div1>
                     <div1 class=" conteiner" >
                        <div class="card" style="width: 16rem;">
                            <h5 class="card-title" style="width: 8rem; margin: 0 0 0 3.0%; float: left;">YOURE SCORE</h5>
                            <p class="card-body" style="margin: 0 0 0 3.0%; float: left; font-size: 30px;">{{ user_estimate }}</p>
                        </div>
                    </div1>
                        {% if not task.score  %}
                    <form
                            class="form-horizontal"
                            action="{{url_for('plannings.tasks.set_score', planning_id=planning_id, task_id=task.uid)}}"
                            method="post"
                        >
                        <div class="card" style="width: 16rem;">
                            <h5 class="card-title" style="width: 8rem; margin: 0 0 0 3.0%; float: left;">TOTAL SCORE</h5>
                            <p class="card-body" style="margin: 0 0 0 3.0%; float: left;">
                            <input
                                id="score"
                                type="text"
                                class="form-control"
                                placeholder="score"
                                name="score"
                            />
                            </p>
                            <button type="submit" class="btn btn-success" style="float: right;">Submit</button>
                        </div>
                    </form>
                {% else %}
                <b>[{{ task.score }}]</b>
                {% endif %}
                        </div1>
                    </div1>
                    <div1 class="card" >
                        <div class="card text-center" style="line-height: 1.5; height: 400px;">
                        <h3 style='text-align: left;'>Storypoint|User</h3>

                            <ul style="list-style-type:none; font-size: 13pt;">
                                {% for estimate in user_estimates %}
                                <li><b>{{ estimate[1] }}</b>: {{ estimate[0] }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div1>
        </body>
</html>

frontend/templates/index.html
<html>
    <head>
        <title>Scrum poker</title>
    </head>
    <body>
        <h1>Hello world!</h1>
    </body>
</html>

frontend/templates/name.html
<html>
    <body>
        <h1> Ваше имя: </h1>
        <ul>
            {%for user in users%}
                <li>Hello, {{ user.username }}!</li>
            {%endfor%}
        </ul>
    </body>
</html>

frontend/templates/plannings.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Scrum poker</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <style>
            li {
                background: #ddd;
                border: 1px solid #ddd;
                padding: 5px;
                margin: 5px;
                width: 200px;
                list-style-type: none;
            }

            .menu li {
                cursor: pointer;
            }
        </style>
    </head>

    <body>
        <div class="jumbotron" style=" text-indent: 30px;">
            <h1>ScrumPY</h1>
            <p>Scrum Poker for You</p>
        </div>
        <div class="container mt-3">
            <button type="button" class="btn btn-outline-dark">
                {{ username }}
            </button>
        </div>
        {% if userid and username %}
        <div class="container">
            <h2>Задачи</h2>

            <div class="well well-lg">
                {% for task in tasks %}
                <a
                    href="{{url_for('plannings.tasks.get_task_by_id', planning_id=planning_id, task_id=task.uid)}}"
                >
                    <ul style="list-style-type: none">
                        <li>
                            {% if task.score %}
                            <b>[{{ task.score }}]</b>
                            {% endif %} {{ task.name }}
                        </li>
                    </ul>
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="container">
            <form
                class="form-horizontal"
                action="{{url_for('plannings.create_task', planning_id=planning_id)}}"
                method="post"
            >
                <div class="form-group" style="width: 500px; right: 16%;">
                    <div class="col-sm-10">
                        <input
                            type="task"
                            class="form-control"
                            id="task"
                            placeholder="Add new task"
                            name="task"
                        />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10" style="position: relative; right: 16.6%;">
                        <button type="submit" class="btn btn-default">
                            Submit
                        </button>
                    </div>
                </div>
            </form>
        </div>
        {% endif %}

        <div class="container">
            <h2>Пользователи</h2>

            <div class="well well-lg">
                {% for user in users %}
                <li>{{ user.name }}</li>
                {% endfor %}
            </div>
        </div>

        {% if not userid or not username %}
        <div class="container mt-3">
            <form
                class="form-horizontal"
                action="{{url_for('plannings.create_user', planning_id=planning_id)}}"
                method="post"
            >
                <div class="form-group">
                    <div class="col-sm-10">
                        <input
                            type="task"
                            class="form-control"
                            id="user"
                            placeholder="Add new user"
                            name="user"
                        />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10" style="position: relative; right: 16.6%;">
                        <button type="submit" class="btn btn-default">
                            Submit
                        </button>
                    </div>
                </div>
            </form>
            {% endif %}
        </div>
    </body>
</html>